### ISSUE TITLE
[Improvement] Refactor the main class for better debugging + releasing .pdb file

### ISSUE THREAD

**Issue by vletoux** [l0ss/Grouper2#88]
While running the program, I got an error:
```
Errors in processing GPOs:
{
  "\\\\xxx.local\\sysvol\\xxx.local\\Policies\\PolicyDefinitions": "System.IndexOutOfRangeException: L'index se trouve en dehors des limites du tableau.\r\n   à Grouper2.Grouper2.<>c__DisplayClass0_1.<Main>b__0()"
}
```

The french translation of the exception is basically an IndexOutOfRangeException.
I tried to locate the error and for that i tried to enable the verbose mode (-v) but it didn't helped.

While reviewing the code & release, I got a couple of suggestions:
The main function is 400 lines long. When it crashes and a stackstrace is generated, it give no useful indication of the error. Try to refactor the code to split this main function in smaller chunck (typically extract the argument parsing code for example).

Then when you release the .exe file, add the .pdb file. It will add the line number and will help spoting the localisation (on Release built, the line number is approximate while in debug built the line number is exact). The stacktrace will then contain the function which did trigger the crash.

Then be sure to log the exception with more details, such as the functional process (the step of the processing), inner exceptions, ... and especially in the debug mode.
I looked at "PolicyDefinitions" in the output and I wasn't able to locate it.
![image](https://user-images.githubusercontent.com/10632326/60668422-38e99700-9e6c-11e9-8dad-4044ca3f33bb.png)

**Comment by l0ss** [comment]
Thanks for the recommendations Vincent, definitely some good suggestions!

I'm going to wait a little while before I try to implement them because another contributor (with much more C# experience than me :-) ) is in the middle of a major refactor of the code which I believe will address some of the issues you raise here.

Once she's finished making those big structural changes I'll come back to this issue and see whether any of your points haven't been addressed yet.

About the "PolicyDefinitions" bug - I can answer this! In the SYSVOL\Policies directory there are all the GPO directories with the GUID style names, and ONE other folder: "PolicyDefinitions". I think it's only present when custom ADMX templates have been added to the environment. It doesn't contain any GPO but Grouper2 tries to treat all subdirectories of SYSVOL\Policies as GPO directories, so it's basically a false positive. I think I can fix it in about 5 mins.

**Comment by klettier** [comment]
Switching to new csproj format would also be a nice feature, I could help with work dispatch if you start an issue with full refactoring tasks.

Cheers

**Comment by l0ss** [comment]
Hi klettier, sorry it took so long for me to see this, don't know why I didn't get a notification for your reply.

Sh3r4 has been doing a huge amount of work restructuring the code to look more like C# and less like PowerShell, and I've just imported all her changes into the dev branch. There are still a bunch of bugs to iron out in dev and the 'pretty' output mode doesn't work at all, but the bones are MUCH better.

If you are keen to help out that would be amazing. The best way to coordinate that is probably to join the #Grouper2 channel on the BloodHound slack. 

You can get an invite here: https://bloodhoundgang.herokuapp.com/

If you'd prefer not to join 'yet another slack' let me know and we can figure out another approach.

**Comment by klettier** [comment]
Hi, thanks for your update I joined the slack group and will start to check the dev branch, I also need a way to mock an Active directory environment to start playing with your tool, I saw that [docker image](https://hub.docker.com/r/dwimberger/ldap-ad-it/) can be used, any advice would be appreciated.

cheers

**Comment by l0ss** [comment]
closing this now we've got the dev branch going properly
